[features]
seeds = false
skip-lint = false
[programs.devnet]
test = "ei1j5p9iBPLfjR5GHsZ1Yd96peCk4F6x2hrFRu7iZDi"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "/home/sjlee80/.config/solana/id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
